# Generated by Django 3.2 on 2021-04-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210418_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'permissions': [('export', 'Can export candidate list')], 'verbose_name': '应聘者', 'verbose_name_plural': '应聘者'},
        ),
    ]
